<a href="https://colab.research.google.com/github/1310NI14L/Bootcamp-From-Python-to-Machine-Learning/blob/main/notebook_J9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jour 9 - 24 Juillet 2026 : Manipulation de Données avec Pandas

**Pandas** est l'outil incontournable pour analyser des données tabulaires (comme des fichiers Excel ou CSV). Il utilise deux structures principales : les **Series** (1 colonne) et les **DataFrames** (un tableau avec des lignes et des colonnes).

In [4]:
import pandas as pd

# Création d'un DataFrame (tableau) à partir d'un dictionnaire
donnees = {
    'Nom': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Ville': ['Paris', 'Lyon', 'Marseille']
}

df = pd.DataFrame(donnees)
df

       Nom  Age      Ville
0    Alice   25      Paris
1      Bob   30       Lyon
2  Charlie   35  Marseille

## Sélection de données
On peut sélectionner une seule colonne avec `df['NomColonne']` ou plusieurs avec une liste de colonnes.

In [5]:
# Sélectionner seulement la colonne Age
print(df['Age'])

# Filtrer les personnes de plus de 28 ans
plus_de_28 = df[df['Age'] > 28]
plus_de_28

0    25
1    30
2    35
Name: Age, dtype: int64

       Nom  Age      Ville
1      Bob   30       Lyon
2  Charlie   35  Marseille

---
## 🏆 Défi du Jour 10

1. Créez un DataFrame `df_employes` contenant 3 employés avec les colonnes : `Nom`, `Salaire`, et `Service`.
2. Affichez uniquement la colonne `Salaire`.
3. Filtrez et affichez uniquement les employés qui gagnent plus de 2500 (inventez les valeurs pour que le filtre fonctionne).

In [11]:
# Écrivez votre code pour le défi ici
employes ={
    'Nom': ['Daniel', 'Bilal', 'Edna'],
    'Salaire': [1500, 2700, 3100],
    'Service': ["DBA & Développeur Back-End", "Développeur Full-Stack & Intégration des composants", "Design UI/UX & Intégration"]
}
df_employes = pd.DataFrame(employes)
print(df_employes['Salaire'])

df_employes[df_employes['Salaire'] > 2500].head()

0    1500
1    2700
2    3100
Name: Salaire, dtype: int64

     Nom  Salaire                                            Service
1  Bilal     2700  Développeur Full-Stack & Intégration des compo...
2   Edna     3100                         Design UI/UX & Intégration