<a href="https://colab.research.google.com/github/1310NI14L/Bootcamp-From-Python-to-Machine-Learning/blob/main/Python_for_Data_Mission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐍 Python for Data — Mission fil rouge
### Bootcamp *From Python to Machine Learning*

**Contexte :** Vous êtes recruté·e comme **Data Analyst** par l'équipe pédagogique.
Votre mission : explorer, **auditer la qualité** et préparer le **Student Performance Dataset**
(performances académiques d'étudiants) pour qu'il soit exploitable — d'abord pour
un rapport d'analyse, puis plus tard pour du Machine Learning.

**Déroulé de la mission (± 2h30) :**

| Étape | Objectif |
|---|---|
| 1 | Charger le CSV |
| 2 | Explorer le DataFrame |
| 3 | Auditer les valeurs manquantes |
| 4 | Auditer qualité (types, doublons, outliers) |
| 5 | Filtrer |
| 6 | Trier |
| 7 | Créer de nouvelles colonnes |
| 8 | Groupby & statistiques |
| 9 | Mini challenge 🎯 |
| 10 | Exporter le dataset prêt pour le ML |

> 💡 **Note pour le speaker** : ce fichier est le **vrai dataset Kaggle/UCI**
> *Student Performance Data* (395 étudiant·es, 33 colonnes), **utilisé tel quel, sans
> aucune modification**. Il se trouve qu'il est déjà propre (0 valeur manquante,
> 0 doublon, types cohérents). Les sections 3 et 4 sont donc formulées comme un
> **audit de qualité** plutôt qu'un nettoyage correctif : les participants apprennent
> à *vérifier* qu'un dataset est propre — un réflexe tout aussi important en vrai
> qu'un nettoyage, et souvent négligé par les débutants qui présument le pire ou
> le meilleur sans jamais contrôler.

In [8]:
# On importe les librairies dont on aura besoin pour toute la mission
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 40)

## 1️⃣ Lecture du CSV

Premier réflexe d'un Data Analyst : **charger les données** et jeter un premier coup d'œil.

In [30]:
df = pd.read_csv("student_performance.csv")
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,course,other,1,2,2,no,yes,yes,no,yes,yes,no,no,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother,2,1,0,no,no,no,no,no,yes,yes,no,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,course,other,1,1,3,no,no,no,no,no,yes,no,no,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother,3,1,0,no,no,no,no,no,yes,yes,no,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father,1,1,0,no,no,no,no,yes,yes,yes,no,3,2,3,3,3,5,5,8,9,9

In [18]:
# Combien de lignes / colonnes ?
df.shape

(395, 33)

## 2️⃣ Exploration du DataFrame

On veut répondre à des questions simples avant de toucher à quoi que ce soit :
- Quelles colonnes ai-je ?
- Quels types de données ?
- Y a-t-il des valeurs bizarres ?

In [19]:
df.columns.tolist()

['school',
 'sex',
 'age',
 'address',
 'famsize',
 'Pstatus',
 'Medu',
 'Fedu',
 'Mjob',
 'Fjob',
 'reason',
 'guardian',
 'traveltime',
 'studytime',
 'failures',
 'schoolsup',
 'famsup',
 'paid',
 'activities',
 'nursery',
 'higher',
 'internet',
 'romantic',
 'famrel',
 'freetime',
 'goout',
 'Dalc',
 'Walc',
 'health',
 'absences',
 'G1',
 'G2',
 'G3']

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [21]:
# Statistiques descriptives sur les colonnes numériques
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [22]:
# Et sur les colonnes catégorielles (texte)
df.describe(include="object")

,school,sex,address,famsize,Pstatus,Mjob,Fjob,reason,guardian,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic
count,395,395,395,395,395,395,395,395,395,395,395,395,395,395,395,395,395
unique,2,2,2,2,2,5,5,4,3,2,2,2,2,2,2,2,2
top,GP,F,U,GT3,T,other,other,course,mother,no,yes,no,yes,yes,yes,yes,no
freq,349,208,307,281,354,141,217,145,273,344,242,214,201,314,375,329,263

❓ **Discussion avec le groupe** : en regardant `df.info()` et `df.describe()`,
qu'est-ce qui vous semble suspect ? (types de colonnes, valeurs min/max, doublons...)

## 3️⃣ Valeurs manquantes

Pandas encode les valeurs manquantes avec `NaN`. **On ne présume jamais** qu'un
dataset en contient ou non — on **vérifie systématiquement**, même quand tout
semble propre au premier coup d'œil.

In [23]:
df.isna().sum().sort_values(ascending=False)

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [ ]:
# En pourcentage, c'est souvent plus parlant (surtout sur de gros datasets)
(df.isna().mean() * 100).round(1).sort_values(ascending=False)

school        0.0
sex           0.0
age           0.0
address       0.0
famsize       0.0
Pstatus       0.0
Medu          0.0
Fedu          0.0
Mjob          0.0
Fjob          0.0
reason        0.0
guardian      0.0
traveltime    0.0
studytime     0.0
failures      0.0
schoolsup     0.0
famsup        0.0
paid          0.0
activities    0.0
nursery       0.0
higher        0.0
internet      0.0
romantic      0.0
famrel        0.0
freetime      0.0
goout         0.0
Dalc          0.0
Walc          0.0
health        0.0
absences      0.0
G1            0.0
G2            0.0
G3            0.0
dtype: float64

❓ **Discussion avec le groupe** : le résultat est 0 partout. Est-ce que ça veut
dire qu'on peut sauter cette étape la prochaine fois ? **Non** — c'est justement
en la faisant systématiquement qu'on peut affirmer avec certitude qu'il n'y a rien
à traiter ici. Un Data Analyst qui saute la vérification sous prétexte que "ça a
l'air propre" prend un risque.

**Pour mémoire, si on avait trouvé des `NaN`, les 3 stratégies classiques auraient été :**

1. **Supprimer** la ligne (`dropna`) — si peu de lignes concernées et donnée critique
2. **Remplacer** par une valeur par défaut (`fillna`) — moyenne, médiane, mode, ou 0
3. **Laisser tel quel** et le signaler — si certains modèles savent gérer les `NaN`

*(pas nécessaire ici, mais gardez ces 3 options en tête pour vos futurs projets)*

## 4️⃣ Nettoyage — audit qualité

Même sans `NaN`, un Data Analyst sérieux contrôle toujours :
- les **types de colonnes** (un nombre stocké en texte, par exemple)
- le **texte mal formaté** (espaces, casse incohérente)
- les **doublons**
- les **valeurs aberrantes** (outliers)

On va passer ce dataset au crible, point par point.

In [24]:
# Les types sont-ils cohérents avec ce qu'on attend ?
# (age, failures, notes... doivent être numériques ; sex, school... du texte)
df.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [25]:
# Zoom sur deux colonnes sensibles : age et sex
print(df["age"].unique())
print(df["sex"].unique())

[18 17 15 16 19 22 20 21]
['F' 'M']

✅ **Résultat de l'audit types/texte** : `age` est bien numérique (pas de "18 ans"
en texte), `sex` ne contient que des valeurs propres (`F`/`M`, pas d'espace ni de
casse incohérente). Rien à corriger — mais on a vérifié, on ne l'a pas supposé.

In [26]:
# Doublons : des lignes strictement identiques ?
df.duplicated().sum()

np.int64(0)

✅ **0 doublon.** Là encore, le réflexe (`.duplicated().sum()`) est plus important
que le résultat : sur un dataset de plusieurs milliers de lignes, des doublons
passent facilement inaperçus si on ne les cherche pas explicitement.

In [27]:
# Valeurs aberrantes potentielles : on regarde la distribution de 'absences'
df["absences"].describe()

count    395.000000
mean       5.708861
std        8.003096
min        0.000000
25%        0.000000
50%        4.000000
75%        8.000000
max       75.000000
Name: absences, dtype: float64

In [32]:
# On regarde les valeurs extrêmes en détail
df.sort_values("absences", ascending=False).head(5)[["age", "sex", "absences"]]

     age sex  absences
276   18   F        75
183   17   F        56
74    16   F        54
315   19   F        40
307   19   M        38

❓ **Discussion avec le groupe** : une valeur de 75 absences interpelle — est-ce
une erreur de saisie ou une situation réelle (décrochage, maladie longue, etc.) ?
**Sans autre information, on ne modifie pas une donnée réelle sur une simple
intuition.** Face à un vrai outlier suspect, le bon réflexe est de se renseigner
(documentation du dataset, personne qui a collecté les données) avant de corriger
quoi que ce soit — supprimer ou plafonner une valeur légitime fausserait l'analyse.
Ici, on **garde la valeur telle quelle** et on la garde en tête pour la suite
(elle pourra par exemple justifier une standardisation avant le Machine Learning).

## 5️⃣ Filtrage

On sélectionne des sous-ensembles de lignes selon des conditions — le pain quotidien
d'un Data Analyst.

In [33]:
# Les étudiants qui veulent poursuivre des études supérieures ET ont internet à la maison
filtre = (df["higher"] == "yes") & (df["internet"] == "yes")
df[filtre].shape[0]

313

In [34]:
# Les étudiants en difficulté : au moins un échec précédent ET note finale < 10
en_difficulte = df[(df["failures"] > 0) & (df["G3"] < 10)]
en_difficulte[["age", "sex", "studytime", "failures", "G3"]].head()

    age sex  studytime  failures  G3
18   17   M          1         3   5
25   16   F          1         2   8
44   16   F          2         1   9
49   15   F          2         1   7
72   15   F          2         2   5

## 6️⃣ Tri

`sort_values` pour classer les étudiants selon un critère.

In [35]:
# Top 5 des meilleures notes finales
df.sort_values("G3", ascending=False)[["age", "sex", "studytime", "G3"]].head()

     age sex  studytime  G3
47    16   M          4  20
286   18   F          3  19
374   18   F          3  19
110   15   M          1  19
8     15   M          2  19

In [ ]:
# Tri multi-critères : par sexe, puis par note décroissante
df.sort_values(["sex", "G3"], ascending=[True, False]).head(8)[["sex", "G3"]]

    sex  G3
286   F  19
374   F  19
91    F  18
198   F  18
260   F  18
293   F  18
303   F  18
182   F  17

## 7️⃣ Création de colonnes

On enrichit le dataset avec des colonnes dérivées — souvent la clé pour un bon modèle
de Machine Learning plus tard.

In [36]:
# Moyenne des 3 notes (G1, G2, G3)
df["moyenne_generale"] = df[["G1", "G2", "G3"]].mean(axis=1).round(2)

# Une colonne catégorielle : l'étudiant a-t-il réussi ? (moyenne >= 10)
df["reussite"] = np.where(df["moyenne_generale"] >= 10, "admis", "non_admis")

# Temps d'écran social/loisir global (sorties + alcool weekend)
df["indice_social"] = df["goout"] + df["Walc"]

df[["G1", "G2", "G3", "moyenne_generale", "reussite", "indice_social"]].head()

   G1  G2  G3  moyenne_generale   reussite  indice_social
0   5   6   6              5.67  non_admis              5
1   5   5   6              5.33  non_admis              4
2   7   8  10              8.33  non_admis              5
3  15  14  15             14.67      admis              3
4   6  10  10              8.67  non_admis              4

## 8️⃣ Groupby & statistiques

`groupby` permet d'agréger les données par catégorie — indispensable pour un rapport
d'analyse.

In [37]:
# Moyenne générale par sexe
df.groupby("sex")["moyenne_generale"].mean().round(2)

sex
F    10.32
M    11.07
Name: moyenne_generale, dtype: float64

In [38]:
# Taux de réussite par temps d'étude hebdomadaire (studytime)
df.groupby("studytime")["reussite"].value_counts(normalize=True).round(2)

studytime  reussite
1          admis        0.54
           non_admis    0.46
2          admis        0.56
           non_admis    0.44
3          admis        0.69
           non_admis    0.31
4          admis        0.70
           non_admis    0.30
Name: proportion, dtype: float64

In [39]:
# Plusieurs statistiques d'un coup avec agg()
df.groupby("sex").agg(
    moyenne=("moyenne_generale", "mean"),
    absences_moy=("absences", "mean"),
    effectif=("moyenne_generale", "count"),
).round(2)

     moyenne  absences_moy  effectif
sex
F      10.32          6.22       208
M      11.07          5.14       187

## 🎯 9️⃣ Mini challenge

**À vous de jouer !** En binôme, répondez aux 3 questions suivantes avec du code Pandas
(15-20 minutes). Utilisez les cellules vides ci-dessous.

1. Quel est le pourcentage d'étudiants qui ont accès à internet **et** qui ont réussi
   (`reussite == "admis"`) ?
2. Quelle catégorie de `Mjob` (métier de la mère) est associée à la meilleure
   `moyenne_generale` ?
3. Créez une nouvelle colonne `soutien_total` qui vaut le nombre de "yes" parmi
   `schoolsup`, `famsup` et `paid` pour chaque étudiant. Quel est son lien avec la
   réussite (`groupby`) ?

In [45]:
taux = ((df["internet"] == "yes") & (df["reussite"] == "admis")).mean() * 100
print(f"Le pourcentage est : {taux:.1f} %")

Le pourcentage est : 50.9 %

In [56]:
# Question 2 : à vous de jouer
df.groupby("Mjob")["moyenne_generale"].mean().sort_values(ascending=False).head(1)

Mjob
health    12.234706
Name: moyenne_generale, dtype: float64

In [66]:
# Question 3 : à vous de jouer
df['soutien_total'] = (df[['schoolsup','famsup','paid']] == 'yes').sum(axis=1)
df.groupby('reussite')['soutien_total'].value_counts(normalize=True)
display(df)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,moyenne_generale,reussite,indice_social,soutien_total
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6,5,6,6,5.67,non_admis,5,1
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4,5,5,6,5.33,non_admis,4,1
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10,7,8,10,8.33,non_admis,5,2
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2,15,14,15,14.67,admis,3,2
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4,6,10,10,8.67,non_admis,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,course,other,1,2,2,no,yes,yes,no,yes,yes,no,no,5,5,4,4,5,4,11,9,9,9,9.00,non_admis,9,2
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother,2,1,0,no,no,no,no,no,yes,yes,no,2,4,5,3,4,2,3,14,16,16,15.33,admis,9,0
392,MS,M,21,R,GT3,T,1,1,other,other,course,other,1,1,3,no,no,no,no,no,yes,no,no,5,5,3,3,3,3,3,10,8,7,8.33,non_admis,6,0
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother,3,1,0,no,no,no,no,no,yes,yes,no,4,4,1,3,4,5,0,11,12,10,11.00,admis,5,0
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father,1,1,0,no,no,no,no,yes,yes,yes,no,3,2,3,3,3,5,5,8,9,9,8.67,non_admis,6,0

<details>
<summary>💡 Solution (speaker only — à ne pas montrer avant la fin du challenge)</summary>

```python
# Q1
pct = (df[df["internet"] == "yes"]["reussite"] == "admis").mean() * 100
print(f"{pct:.1f} %")

# Q2
df.groupby("Mjob")["moyenne_generale"].mean().sort_values(ascending=False)

# Q3
supports = ["schoolsup", "famsup", "paid"]
df["soutien_total"] = (df[supports] == "yes").sum(axis=1)
df.groupby("soutien_total")["reussite"].value_counts(normalize=True)
```
</details>

## 🔟 Préparation du dataset pour le Machine Learning

On termine en sauvegardant une version propre et enrichie du dataset : c'est elle qui
sera réutilisée dans les ateliers **Machine Learning Démystifié** et **ML Day**.

In [67]:
df.to_csv("student_performance_clean.csv", index=False)
print("✅ Dataset propre exporté :", df.shape)

✅ Dataset propre exporté : (395, 37)

## ✅ Récapitulatif

Vous avez, comme un·e vrai·e Data Analyst :
- chargé et exploré un dataset réel
- **audité** les valeurs manquantes, les types, les doublons et les outliers (et prouvé qu'il n'y avait rien à corriger)
- filtré, trié, créé des colonnes
- produit des statistiques de groupe
- livré un dataset validé, prêt pour le Machine Learning 🚀

**Prochaine étape du bootcamp : Machine Learning Démystifié**, avec ce même dataset !